/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-08-11 09:25:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\" />\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\n");
      out.write("<link rel=\"shortcut icon\" href=\"favicon.ico\"/>\n");
      out.write("<link rel=\"bookmark\" href=\"favicon.ico\"/>\n");
      out.write("<link href=\"h-ui/css/H-ui.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"h-ui/css/H-ui.login.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"h-ui/lib/icheck/icheck.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<link href=\"h-ui/lib/Hui-iconfont/1.0.1/iconfont.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script> \n");
      out.write("<script type=\"text/javascript\" src=\"h-ui/js/H-ui.js\"></script> \n");
      out.write("<script type=\"text/javascript\" src=\"h-ui/lib/icheck/jquery.icheck.min.js\"></script> \n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(function(){\n");
      out.write("		//点击图片切换验证码\n");
      out.write("		$(\"#vcodeImg\").click(function(){\n");
      out.write("			this.src=\"LoginServlet?method=GetVCode&t=\"+new Date().getTime();\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		$(document).ready(function(){\n");
      out.write("	        const urlParams = new URLSearchParams(window.location.search);\n");
      out.write("	        const logoutStatus = urlParams.get('logout');\n");
      out.write("	        \n");
      out.write("	        if(logoutStatus === 'success') {\n");
      out.write("	            $.messager.alert(\"消息提醒\", \"退出成功!\", \"info\");\n");
      out.write("	        }\n");
      out.write("	    });\n");
      out.write("		\n");
      out.write("		//登录\n");
      out.write("		$(\"#submitBtn\").click(function(){\n");
      out.write("			if($(\"#radio-2\").attr(\"checked\") && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${systemInfo.forbidStudent}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == 1){\n");
      out.write("				$.messager.alert(\"消息提醒\", \"学生暂不能登录系统！\", \"warning\");\n");
      out.write("				return;\n");
      out.write("			}\n");
      out.write("			if($(\"#radio-3\").attr(\"checked\") && \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${systemInfo.forbidTeacher}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == 1){\n");
      out.write("				$.messager.alert(\"消息提醒\", \"教师暂不能登录系统！\", \"warning\");\n");
      out.write("				return;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var data = $(\"#form\").serialize();\n");
      out.write("			$.ajax({\n");
      out.write("				type: \"post\",\n");
      out.write("				url: \"LoginServlet?method=Login\",\n");
      out.write("				data: data, \n");
      out.write("				dataType: \"text\",\n");
      out.write("				success: function(msg){\n");
      out.write("					if(\"vcodeError\" == msg){\n");
      out.write("						$.messager.alert(\"消息提醒\", \"验证码错误!\", \"warning\");\n");
      out.write("						$(\"#vcodeImg\").click();\n");
      out.write("						$(\"input[name='vcode']\").val(\"\");\n");
      out.write("					} else if(\"loginError\" == msg){\n");
      out.write("						$.messager.alert(\"消息提醒\", \"用户名或密码错误!\", \"warning\");\n");
      out.write("						$(\"#vcodeImg\").click();\n");
      out.write("						$(\"input[name='vcode']\").val(\"\");					\n");
      out.write("					} \n");
      out.write("					else if(\"admin\" == msg){\n");
      out.write("						window.location.href = \"LoginServlet?method=AdminView\";\n");
      out.write("					} else if(\"student\" == msg){\n");
      out.write("						window.location.href = \"LoginServlet?method=StudentView\";\n");
      out.write("					} else if(\"teacher\" == msg){\n");
      out.write("						window.location.href = \"LoginServlet?method=TeacherView\";\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("		//设置复选框\n");
      out.write("		$(\".skin-minimal input\").iCheck({\n");
      out.write("			radioClass: 'iradio-blue',\n");
      out.write("			increaseArea: '25%'\n");
      out.write("		});\n");
      out.write("	})\n");
      out.write("</script> \n");
      out.write("<title>登录|郑州大学教务系统</title>\n");
      out.write("<meta name=\"keywords\" content=\"成绩管理系统\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"header\" style=\"padding: 0;\">\n");
      out.write("	<h2 style=\"color: white; width: 400px; height: 60px; line-height: 60px; margin: 0 0 0 30px; padding: 0;\"><img src=\"zzuLogo.png\" alt=\"Icon\" style=\"vertical-align:middle; margin-right: 10px; width: 50px; height: 50px;\" />郑州大学教务系统</h2>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("<div class=\"loginWraper\">\n");
      out.write("  <div id=\"loginform\" class=\"loginBox\">\n");
      out.write("    <form id=\"form\" class=\"form form-horizontal\" method=\"post\">\n");
      out.write("      <div class=\"row cl\">\n");
      out.write("        <label class=\"form-label col-3\"><i class=\"Hui-iconfont\">&#xe60d;</i></label>\n");
      out.write("        <div class=\"formControls col-8\">\n");
      out.write("          <input id=\"\" name=\"account\" type=\"text\" placeholder=\"用户名\" class=\"input-text size-L\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row cl\">\n");
      out.write("        <label class=\"form-label col-3\"><i class=\"Hui-iconfont\">&#xe60e;</i></label>\n");
      out.write("        <div class=\"formControls col-8\">\n");
      out.write("          <input id=\"\" name=\"password\" type=\"password\" placeholder=\"密码\" class=\"input-text size-L\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row cl\">\n");
      out.write("        <div class=\"formControls col-8 col-offset-3\">\n");
      out.write("          <input class=\"input-text size-L\" name=\"vcode\" type=\"text\" placeholder=\"请输入验证码\" style=\"width: 200px;\">\n");
      out.write("          <img title=\"点击图片切换验证码\" id=\"vcodeImg\" src=\"LoginServlet?method=GetVCode\"></div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"mt-20 skin-minimal\" style=\"text-align: center;\">\n");
      out.write("		<div class=\"radio-box\">\n");
      out.write("			<input type=\"radio\" id=\"radio-2\" name=\"type\" checked value=\"0\" />\n");
      out.write("			<label for=\"radio-1\">学生</label>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"radio-box\">\n");
      out.write("			<input type=\"radio\" id=\"radio-3\" name=\"type\" value=\"1\" />\n");
      out.write("			<label for=\"radio-2\">老师</label>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"radio-box\">\n");
      out.write("			<input type=\"radio\" id=\"radio-1\" name=\"type\" value=\"2\" />\n");
      out.write("			<label for=\"radio-3\">管理员</label>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("      \n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"formControls col-8 col-offset-3\">\n");
      out.write("          <input id=\"submitBtn\" type=\"button\" class=\"btn btn-success radius size-L\" value=\"&nbsp;登&nbsp;&nbsp;&nbsp;&nbsp;录&nbsp;\">\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"footer\">zzu.admin</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
