/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-08-06 13:41:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.teacher;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class courseScore_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>考试列表</title>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/css/demo.css\">\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/themes/locale/easyui-lang-zh_CN.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		//验证只能为数字\n");
      out.write("		function scoreBlur(score){\n");
      out.write("			if(!/^[1-9]\\d*$/.test($(score).val())){\n");
      out.write("				$(score).val(\"\");\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("	$(function() {	\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		var table;\n");
      out.write("		\n");
      out.write("		//datagrid初始化 \n");
      out.write("	    $('#dataList').datagrid({ \n");
      out.write("	        title:'课程列表', \n");
      out.write("	        iconCls:'icon-more',//图标 \n");
      out.write("	        border: true, \n");
      out.write("	        collapsible: false,//是否可折叠的 \n");
      out.write("	        fit: true,//自动大小 \n");
      out.write("	        method: \"post\",\n");
      out.write("	        url:\"TeacherServlet?method=courseList\",\n");
      out.write("	        idField:'id', \n");
      out.write("	        singleSelect: true,//是否单选 \n");
      out.write("	        pagination: false,//分页控件 \n");
      out.write("	        rownumbers: true,//行号 \n");
      out.write("	        remoteSort: false,\n");
      out.write("	        columns: [[  \n");
      out.write("				{field:'chk',checkbox: true,width:50},\n");
      out.write(" 		        {field:'cno',title:'课程编号',width:100, sortable: true}, \n");
      out.write(" 		        {field:'cname',title:'课程名',width:200, sortable: true},   \n");
      out.write(" 		        {field:'ccredit',title:'课程学分',width:100},\n");
      out.write(" 		        {field:'chour',title:'课程学时',width:100},\n");
      out.write(" 		        {field:'cdate',title:'开课学期',width:150},\n");
      out.write(" 		        {field:'cway',title:'考核形式',width:100}\n");
      out.write("	 		]], \n");
      out.write("	        toolbar: \"#toolbar\"\n");
      out.write("	    }); 	\n");
      out.write("\n");
      out.write("	    //成绩统计\n");
      out.write("	   $(\"#escore\").click(function(){\n");
      out.write("	    	var exam = $(\"#dataList\").datagrid(\"getSelected\");	    	\n");
      out.write("        	if(exam == null){\n");
      out.write("            	$.messager.alert(\"消息提醒\", \"请选择课程!\", \"warning\");\n");
      out.write("            } else{           	            		\n");
      out.write("               		setTimeout(function(){               		\n");
      out.write("                		var data = {cno:exam.cno};              \n");
      out.write("    			    	setTimeout(function(){\n");
      out.write("    				    	$(\"#escoreList\").datagrid(\"options\").url = \"TeacherServlet?method=scoreList\";\n");
      out.write("    				    	$(\"#escoreList\").datagrid(\"options\").queryParams = data;\n");
      out.write("    				    	$(\"#escoreList\").datagrid(\"reload\");\n");
      out.write("    			    	}, 30)	\n");
      out.write("    			    	setTimeout(function(){\n");
      out.write("    				    	$(\"#escoreListDialog\").dialog(\"open\");\n");
      out.write("    			    	}, 80)\n");
      out.write("    			    	\n");
      out.write("                	}, 100);\n");
      out.write("               		\n");
      out.write("            	}\n");
      out.write("\n");
      out.write("	    });\n");
      out.write("	    	  	\n");
      out.write("	  	//考试成绩窗口\n");
      out.write("	    $(\"#escoreListDialog\").dialog({\n");
      out.write("	    	title: \"成绩统计\",\n");
      out.write("	    	width: 850,\n");
      out.write("	    	height: 550,\n");
      out.write("	    	iconCls: \"icon-chart_bar\",\n");
      out.write("	    	modal: true,\n");
      out.write("	    	collapsible: false,\n");
      out.write("	    	minimizable: false,\n");
      out.write("	    	maximizable: false,\n");
      out.write("	    	draggable: true,\n");
      out.write("	    	closed: true,\n");
      out.write("	    });\n");
      out.write("	  	//成绩列表\n");
      out.write("	    $(\"#escoreList, #regEscoreList\").datagrid({ \n");
      out.write("   	        border: true, \n");
      out.write("   	        collapsible: false,//是否可折叠的 \n");
      out.write("   	        fit: true,//自动大小 \n");
      out.write("   	        method: \"post\",\n");
      out.write("   	        noheader: true,\n");
      out.write("   	        singleSelect: true,//是否单选 \n");
      out.write("   	        rownumbers: true,//行号 \n");
      out.write("   	        sortOrder:'DESC', \n");
      out.write("   	        remoteSort: false,\n");
      out.write("   	        frozenColumns: [[  \n");
      out.write("   	        	{field:'cno',title:'课程代码',width:100,resizable:false, sortable:true},\n");
      out.write("   	        	{field:'cname', title:'课程名',width:150,resizable:false},\n");
      out.write("   				{field:'sno',title:'学号',width:120,resizable: false, sortable:true},    \n");
      out.write("   				{field:'sname',title:'姓名',width:120,resizable: false},        \n");
      out.write("   				{field:'score',title:'成绩',width:120,resizable: false, sortable:true},\n");
      out.write("   				{field:'cdate',title:'学期',width:150,resizable:false}\n");
      out.write("   			]],\n");
      out.write("   	    });\n");
      out.write("	  	\n");
      out.write("	    $(\"#escoreList\").datagrid({ \n");
      out.write("   	        toolbar: \"#escoreToolbar\",\n");
      out.write("   	    });\n");
      out.write("	    \n");
      out.write("	    $(\"#regEscoreList\").datagrid({ \n");
      out.write("   	        toolbar: \"#regEscoreToolbar\",\n");
      out.write("   	    });\n");
      out.write("	  	\n");
      out.write("	  	//考试成绩窗口\n");
      out.write("	    $(\"#regEscoreDialog\").dialog({\n");
      out.write("	    	title: \"成绩登记\",\n");
      out.write("	    	width: 850,\n");
      out.write("	    	height: 550,\n");
      out.write("	    	iconCls: \"icon-vcard-edit\",\n");
      out.write("	    	modal: true,\n");
      out.write("	    	collapsible: false,\n");
      out.write("	    	minimizable: false,\n");
      out.write("	    	maximizable: false,\n");
      out.write("	    	draggable: true,\n");
      out.write("	    	closed: true,\n");
      out.write("	    \n");
      out.write("	    });  \n");
      out.write("	  	\n");
      out.write("	  	// 导出数据按钮\n");
      out.write("	  	$(\"#exportCourseScore\").click(function(){\n");
      out.write("	  		var exam = $(\"#dataList\").datagrid(\"getSelected\");\n");
      out.write("	  		if (exam == null) {\n");
      out.write("				$.messager.alert(\"消息提醒\", \"请选择课程!\", \"warning\");\n");
      out.write("				return;\n");
      out.write("			}\n");
      out.write("			window.location.href = \"TeacherServlet?method=exportCourseScore&cno=\" + exam.cno;\n");
      out.write("	  	});\n");
      out.write("	});\n");
      out.write("	</script>\n");
      out.write("	<style>\n");
      out.write("		#toolbar {\n");
      out.write("			overflow: hidden;\n");
      out.write("			padding: 5px;\n");
      out.write("		}\n");
      out.write("		#toolbar div {\n");
      out.write("			float: left;\n");
      out.write("			margin-right: 10px;\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 数据列表 -->\n");
      out.write("	<table id=\"dataList\" cellspacing=\"0\" cellpadding=\"0\"> \n");
      out.write("	    \n");
      out.write("	</table> \n");
      out.write("	\n");
      out.write("	<!-- 工具栏 -->\n");
      out.write("	<div id=\"toolbar\">\n");
      out.write("		<div><a id=\"escore\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-chart_bar',plain:true\">成绩统计</a></div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<!-- 考试成绩表 -->\n");
      out.write("	<div id=\"escoreListDialog\">\n");
      out.write("		<table id=\"escoreList\" cellspacing=\"0\" cellpadding=\"0\"> \n");
      out.write("	    \n");
      out.write("		</table> \n");
      out.write("		<div id=\"escoreToolbar\">\n");
      out.write("			<a id=\"exportCourseScore\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-print',plain:true\" style=\"float:right;\">导出数据</a>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	</div>	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
