/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-08-11 09:32:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.teacher;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class teacher_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("    <title>教师|郑州大学教务系统</title>\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\"/>\n");
      out.write("	<link rel=\"bookmark\" href=\"favicon.ico\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/css/default.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\" />\n");
      out.write("    <script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src='easyui/js/outlook2.js'> </script>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("	var _menus = \n");
      out.write("	{\n");
      out.write("		\"menus\":\n");
      out.write("		[\n");
      out.write("			{\n");
      out.write("				\"menuid\":\"1\",\"icon\":\"\",\"menuname\":\"信息查询\",\n");
      out.write("				\"menus\":[			\n");
      out.write("							{\"menuid\":\"11\",\"menuname\":\"个人信息\",\"icon\":\"icon-password\",\"url\":\"TeacherServlet?method=TeacherPersonalView\"},\n");
      out.write("							\n");
      out.write("							{\"menuid\":\"12\",\"menuname\":\"成绩录入\",\"icon\":\"icon-find\",\"url\":\"TeacherServlet?method=ScoreManageView\"},					      \n");
      out.write("						]\n");
      out.write("			},\n");
      out.write("			{\"menuid\":\"2\",\"icon\":\"\",\"menuname\":\"课程\",\n");
      out.write("				\"menus\":[\n");
      out.write("						{\"menuid\":\"21\",\"menuname\":\"成绩查询\",\"icon\":\"icon-note\",\"url\":\"TeacherServlet?method=CourseScoreView\"},\n");
      out.write("					]\n");
      out.write("			},\n");
      out.write("			{\n");
      out.write("				\"menuid\":\"3\",\"icon\":\"\",\"menuname\":\"课表查询\",\n");
      out.write("				\"menus\":[\n");
      out.write("							{\"menuid\":\"21\",\"menuname\":\"教学课表\",\"icon\":\"icon-note\",\"url\":\"TeacherServlet?method=CourseListView\"},					\n");
      out.write("						]\n");
      out.write("			}\n");
      out.write("		]\n");
      out.write("	};\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body class=\"easyui-layout\" style=\"overflow-y: hidden\"  scroll=\"no\">\n");
      out.write("	<noscript>\n");
      out.write("		<div style=\" position:absolute; z-index:100000; height:2046px;top:0px;left:0px; width:100%; background:white; text-align:center;\">\n");
      out.write("		    <img src=\"images/noscript.gif\" alt='抱歉，请开启脚本支持！' />\n");
      out.write("		</div>\n");
      out.write("	</noscript>\n");
      out.write("    <div region=\"north\" split=\"true\" border=\"false\" style=\"overflow: hidden; height: 30px;\n");
      out.write("        background: url(images/layout-browser-hd-bg.gif) #7f99be repeat-x center 50%;\n");
      out.write("        line-height: 20px;color: #fff; font-family: Verdana, 微软雅黑,黑体\">\n");
      out.write("        <span style=\"float:right; padding-right:20px;\" class=\"head\"><span style=\"color:normal; font-weight:bold;\">欢迎您,");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tno}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")&nbsp;&nbsp;&nbsp;&nbsp;管理员</span>&nbsp;&nbsp;&nbsp;<a href=\"#\" id=\"loginOut\" onclick=\"confirmLogout()\">安全退出</a></span>\n");
      out.write("        <span style=\"padding-left:10px; font-size: 16px; \"><img src=\"zzuLogo.png\" alt=\"Icon\" style=\"vertical-align:middle; margin-right: 5px; width: 20px; height: 20px;\" />郑州大学教务系统 </span>\n");
      out.write("    	<script type=\"text/javascript\">\n");
      out.write("		    function confirmLogout() {\n");
      out.write("		        var result = confirm(\"确认退出吗？\");\n");
      out.write("		        if (result) {\n");
      out.write("		            window.location.href = \"LoginServlet?method=LoginOut\";\n");
      out.write("		        }\n");
      out.write("		    }\n");
      out.write("		</script>\n");
      out.write("    </div>\n");
      out.write("    <div region=\"west\" hide=\"true\" split=\"true\" title=\"导航菜单\" style=\"width:180px;\" id=\"west\">\n");
      out.write("	<div id=\"nav\" class=\"easyui-accordion\" fit=\"true\" border=\"false\">\n");
      out.write("		<!--  导航内容 -->\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("    </div>\n");
      out.write("    <div id=\"mainPanle\" region=\"center\" style=\"background: #eee; overflow-y:hidden\">\n");
      out.write("        <div id=\"tabs\" class=\"easyui-tabs\"  fit=\"true\" border=\"false\" ></div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
