/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-07-10 09:23:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class courseList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>课程列表</title>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/css/demo.css\">\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/js/validateExtends.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("	$(function() {	\n");
      out.write("		//datagrid初始化 \n");
      out.write("	    $('#dataList').datagrid({ \n");
      out.write("	        title:'课程列表', \n");
      out.write("	        iconCls:'icon-more',//图标 \n");
      out.write("	        border: true, \n");
      out.write("	        collapsible:false,//是否可折叠的 \n");
      out.write("	        fit: true,//自动大小 \n");
      out.write("	        method: \"post\",\n");
      out.write("	        url:\"AdminServlet?method=courseList\",\n");
      out.write("	        idField:'tno', \n");
      out.write("	        singleSelect:false,//是否单选 \n");
      out.write("	        pagination:true,//分页控件 \n");
      out.write("	        rownumbers:true,//行号 \n");
      out.write("	        sortName:'cno',\n");
      out.write("	        sortOrder:'ASC', \n");
      out.write("	        remoteSort: false,\n");
      out.write("	        columns: [[  \n");
      out.write("				{field:'chk',checkbox: true,width:50},		       \n");
      out.write(" 		        {field:'cno',title:'课程代码',width:100, sortable:true},    \n");
      out.write(" 		        {field:'cname',title:'课程名',width:150},\n");
      out.write(" 		        {field:'tname',title:'任课教师',width:100},\n");
      out.write(" 		        {field:'chour',title:'学时',width:100},\n");
      out.write(" 		        {field:'ccredit',title:'学分',width:50},  \n");
      out.write("		        {field:'cway',title:'考核方式',width:100},\n");
      out.write(" 		        {field:'cdate',title:'学期',width:200},\n");
      out.write("	 		]], \n");
      out.write("	        toolbar: \"#toolbar\"\n");
      out.write("	    }); \n");
      out.write("	    //设置分页控件 \n");
      out.write("	    var p = $('#dataList').datagrid('getPager'); \n");
      out.write("	    $(p).pagination({ \n");
      out.write("	        pageSize: 10,//每页显示的记录条数，默认为10 \n");
      out.write("	        pageList: [10,20,30,50,100],//可以设置每页记录条数的列表 \n");
      out.write("	        beforePageText: '第',//页数文本框前显示的汉字 \n");
      out.write("	        afterPageText: '页    共 {pages} 页', \n");
      out.write("	        displayMsg: '当前显示 {from} - {to} 条记录   共 {total} 条记录', \n");
      out.write("	    }); \n");
      out.write("	    //修改\n");
      out.write("	    $(\"#add\").click(function(){\n");
      out.write("	    	$(\"#addDialog\").dialog(\"open\");\n");
      out.write("	    });\n");
      out.write("	    $(\"#edit\").click(function(){\n");
      out.write("	    	var selectRows = $(\"#dataList\").datagrid(\"getSelections\");\n");
      out.write("        	if(selectRows.length != 1){\n");
      out.write("            	$.messager.alert(\"消息提醒\", \"请选择一条数据进行操作!\", \"warning\");\n");
      out.write("            } else{\n");
      out.write("		    	$(\"#editDialog\").dialog(\"open\");\n");
      out.write("            }\n");
      out.write("	    });\n");
      out.write("	  	//删除\n");
      out.write("	    $(\"#delete\").click(function(){\n");
      out.write("	    	var selectRow = $(\"#dataList\").datagrid(\"getSelected\");\n");
      out.write("        	if(selectRow == null){\n");
      out.write("            	$.messager.alert(\"消息提醒\", \"请选择数据进行删除!\", \"warning\");\n");
      out.write("            } else{\n");
      out.write("            	var courseid = selectRow.cno;\n");
      out.write("            	$.messager.confirm(\"消息提醒\", \"将删除与课程相关的所有数据，确认继续？\", function(r){\n");
      out.write("            		if(r){\n");
      out.write("            			$.ajax({\n");
      out.write("							type: \"post\",\n");
      out.write("							url: \"AdminServlet?method=deleteCourse\",\n");
      out.write("							data: {courseid: courseid},\n");
      out.write("							success: function(msg){\n");
      out.write("								if(msg == \"success\"){\n");
      out.write("									$.messager.alert(\"消息提醒\",\"删除成功!\",\"info\");\n");
      out.write("									//刷新表格\n");
      out.write("									$(\"#dataList\").datagrid(\"reload\");\n");
      out.write("									$(\"#dataList\").datagrid(\"uncheckAll\");\n");
      out.write("								} else{\n");
      out.write("									$.messager.alert(\"消息提醒\",\"删除失败!\",\"warning\");\n");
      out.write("									return;\n");
      out.write("								}\n");
      out.write("							}\n");
      out.write("						});\n");
      out.write("            		}\n");
      out.write("            	});\n");
      out.write("            }\n");
      out.write("	    });\n");
      out.write("	  	\n");
      out.write("	  //导出按钮事件\n");
      out.write("	    $(\"#export\").click(function(){\n");
      out.write("	    	var url = \"AdminServlet?method=exportCourseList\";\n");
      out.write("	    	window.location.href = url;\n");
      out.write("	    });\n");
      out.write("	  \n");
      out.write("	  	//设置添加\n");
      out.write("	    $(\"#addDialog\").dialog({\n");
      out.write("	    	title: \"添加课程\",\n");
      out.write("	    	width: 650,\n");
      out.write("	    	height: 460,\n");
      out.write("	    	iconCls: \"icon-add\",\n");
      out.write("	    	modal: true,\n");
      out.write("	    	collapsible: false,\n");
      out.write("	    	minimizable: false,\n");
      out.write("	    	maximizable: false,\n");
      out.write("	    	draggable: true,\n");
      out.write("	    	closed: true,\n");
      out.write("	    	buttons: [\n");
      out.write("	    		{\n");
      out.write("					text:'添加',\n");
      out.write("					plain: true,\n");
      out.write("					iconCls:'icon-user_add',\n");
      out.write("					handler:function(){\n");
      out.write("						var validate = $(\"#addForm\").form(\"validate\");\n");
      out.write("						if(!validate){\n");
      out.write("							$.messager.alert(\"消息提醒\",\"请检查你输入的数据!\",\"warning\");\n");
      out.write("							return;\n");
      out.write("						} else{\n");
      out.write("							$.ajax({\n");
      out.write("								type: \"post\",\n");
      out.write("								url: \"AdminServlet?method=addCourse\",\n");
      out.write("								data: $(\"#addForm\").serialize(),\n");
      out.write("								success: function(msg){\n");
      out.write("									if(msg == \"success\"){\n");
      out.write("										$.messager.alert(\"消息提醒\",\"添加成功!\",\"info\");\n");
      out.write("										//关闭窗口\n");
      out.write("										$(\"#addDialog\").dialog(\"close\");\n");
      out.write("										//清空原表格数据\n");
      out.write("										$(\"#add_cno\").textbox('setValue', \"\");\n");
      out.write("										$(\"#add_cname\").textbox('setValue', \"\");\n");
      out.write("										$(\"#add_tname\").textbox('setValue', \"\");\n");
      out.write("										$(\"#add_chour\").textbox('setValue', \"\");\n");
      out.write("										$(\"#add_credit\").textbox('setValue', \"\");\n");
      out.write("										$(\"#add_cway\").textbox('setValue', \"\");\n");
      out.write("										$(\"#add_cdate\").textbox('setValue', \"\");\n");
      out.write("										//重新刷新页面数据\n");
      out.write("							  			$('#dataList').datagrid(\"reload\");	\n");
      out.write("							  			$(\"#dataList\").datagrid(\"uncheckAll\");\n");
      out.write("									} else{\n");
      out.write("										$.messager.alert(\"消息提醒\",\"添加失败!\",\"warning\");\n");
      out.write("										return;\n");
      out.write("									}\n");
      out.write("								}\n");
      out.write("							});\n");
      out.write("						}\n");
      out.write("					}\n");
      out.write("				},\n");
      out.write("				{\n");
      out.write("					text:'重置',\n");
      out.write("					plain: true,\n");
      out.write("					iconCls:'icon-reload',\n");
      out.write("					handler:function(){\n");
      out.write("						$(\"#add_cno\").textbox('setValue', \"\");\n");
      out.write("						$(\"#add_cname\").textbox('setValue', \"\");\n");
      out.write("						$(\"#add_tname\").textbox('setValue', \"\");\n");
      out.write("						$(\"#add_chour\").textbox('setValue', \"\");\n");
      out.write("						$(\"#add_credit\").textbox('setValue', \"\");\n");
      out.write("						$(\"#add_cway\").textbox('setValue', \"\");\n");
      out.write("						$(\"#add_cdate\").textbox('setValue', \"\");	\n");
      out.write("					}\n");
      out.write("				},\n");
      out.write("			]\n");
      out.write("	    });\n");
      out.write("\n");
      out.write("		//设置编辑\n");
      out.write("	    $(\"#editDialog\").dialog({\n");
      out.write("	    	title: \"课程信息\",\n");
      out.write("	    	width: 650,\n");
      out.write("	    	height: 460,\n");
      out.write("	    	iconCls: \"icon-edit\",\n");
      out.write("	    	modal: true,\n");
      out.write("	    	collapsible: false,\n");
      out.write("	    	minimizable: false,\n");
      out.write("	    	maximizable: false,\n");
      out.write("	    	draggable: true,\n");
      out.write("	    	closed: true,\n");
      out.write("	    	buttons: [\n");
      out.write("	    		{\n");
      out.write("					text:'提交',\n");
      out.write("					plain: true,\n");
      out.write("					iconCls:'icon-user_add',\n");
      out.write("					handler:function(){\n");
      out.write("						var validate = $(\"#editForm\").form(\"validate\");\n");
      out.write("						if(!validate){\n");
      out.write("							$.messager.alert(\"消息提醒\",\"请检查你输入的数据!\",\"warning\");\n");
      out.write("							return;\n");
      out.write("						} else{\n");
      out.write("							$.ajax({\n");
      out.write("								type: \"post\",\n");
      out.write("								url: \"AdminServlet?method=editCourse\",\n");
      out.write("								data: $(\"#editForm\").serialize(),\n");
      out.write("								success: function(msg){\n");
      out.write("									if(msg == \"success\"){\n");
      out.write("										$.messager.alert(\"消息提醒\",\"更新成功!\",\"info\");\n");
      out.write("										//关闭窗口\n");
      out.write("										$(\"#editDialog\").dialog(\"close\");\n");
      out.write("										//刷新表格\n");
      out.write("										$(\"#dataList\").datagrid(\"reload\");\n");
      out.write("										$(\"#dataList\").datagrid(\"uncheckAll\");						  			\n");
      out.write("									} else{\n");
      out.write("										$.messager.alert(\"消息提醒\",\"更新失败!\",\"warning\");\n");
      out.write("										return;\n");
      out.write("									}\n");
      out.write("								}\n");
      out.write("							});\n");
      out.write("						}\n");
      out.write("					}\n");
      out.write("				},\n");
      out.write("				{\n");
      out.write("					text:'重置',\n");
      out.write("					plain: true,\n");
      out.write("					iconCls:'icon-reload',\n");
      out.write("					handler:function(){\n");
      out.write("						//清空表单\n");
      out.write("						$(\"#edit_cno\").textbox('setValue', selectRow.cno);\n");
      out.write("						$(\"#edit_cname\").textbox('setValue', selectRow.cname);\n");
      out.write("						$(\"#edit_tname\").textbox('setValue', selectRow.tname);\n");
      out.write("						$(\"#edit_chour\").textbox('setValue', selectRow.chour);\n");
      out.write("						$(\"#edit_credit\").textbox('setValue', selectRow.ccredit);\n");
      out.write("						$(\"#edit_cway\").textbox('setValue', selectRow.cway);\n");
      out.write("						$(\"#edit_cdate\").textbox('setValue', selectRow.cdate);	\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			],\n");
      out.write("			onBeforeOpen: function(){\n");
      out.write("				var selectRow = $(\"#dataList\").datagrid(\"getSelected\");\n");
      out.write("				//设置值\n");
      out.write("				$(\"#edit_cno\").textbox('setValue', selectRow.cno);\n");
      out.write("				$(\"#edit_cname\").textbox('setValue', selectRow.cname);\n");
      out.write("				$(\"#edit_tname\").textbox('setValue', selectRow.tname);\n");
      out.write("				$(\"#edit_chour\").textbox('setValue', selectRow.chour);\n");
      out.write("				$(\"#edit_credit\").textbox('setValue', selectRow.ccredit);\n");
      out.write("				$(\"#edit_cway\").textbox('setValue', selectRow.cway);\n");
      out.write("				$(\"#edit_cdate\").textbox('setValue', selectRow.cdate);	\n");
      out.write("			}\n");
      out.write("	    });\n");
      out.write("	});\n");
      out.write("	</script>\n");
      out.write("	<style>\n");
      out.write("		#toolbar {\n");
      out.write("			overflow: hidden;\n");
      out.write("			padding: 5px;\n");
      out.write("		}\n");
      out.write("		#toolbar div {\n");
      out.write("			float: left;\n");
      out.write("			margin-right: 10px;\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 课程列表 -->\n");
      out.write("	<table id=\"dataList\" cellspacing=\"0\" cellpadding=\"0\"> \n");
      out.write("	    \n");
      out.write("	</table> \n");
      out.write("	<!-- 工具栏 -->\n");
      out.write("	<div id=\"toolbar\">\n");
      out.write("		<div style=\"float: left;\"><a id=\"add\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add',plain:true\">添加</a></div>\n");
      out.write("			<div style=\"float: left;\" class=\"datagrid-btn-separator\"></div>\n");
      out.write("		<div style=\"float: left;\"><a id=\"edit\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-edit',plain:true\">修改</a></div>\n");
      out.write("			<div style=\"float: left;\" class=\"datagrid-btn-separator\"></div>\n");
      out.write("		<div><a id=\"delete\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-some-delete',plain:true\">删除</a></div>\n");
      out.write("		<div style=\"float: right;\"><a id=\"export\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-print',plain:true\">导出数据</a></div>\n");
      out.write("	</div>\n");
      out.write("	<div id=\"addDialog\" style=\"padding: 10px\">\n");
      out.write("    	<form id=\"addForm\" method=\"post\">\n");
      out.write("	    	<table cellpadding=\"8\" >\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>课程代码:</td>\n");
      out.write("	    			<td><input id=\"add_cno\" class=\"easyui-textbox\" style=\"width: 200px; height: 30px;\" type=\"text\" name=\"cno\"  data-options=\"required:true,missingMessage:'请输入编号'\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>课程名:</td>\n");
      out.write("	    			<td><input id=\"add_cname\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"cname\" data-options=\"required:true, missingMessage:'请填写课程名'\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>任课教师:</td>\n");
      out.write("	    			<td><input id=\"add_tname\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"tname\" data-options=\"required:true, missingMessage:'请填写任课教师名'\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>学时:</td>\n");
      out.write("	    			<td><input id=\"add_chour\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"chour\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>学分:</td>\n");
      out.write("	    			<td><input id=\"add_credit\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"credit\"/></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>考核形式:</td>\n");
      out.write("	    			<td><input id=\"add_cway\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"cway\"/></td>\n");
      out.write("	    		</tr>  \n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>学期:</td>\n");
      out.write("	    			<td><input id=\"add_cdate\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"cdate\"/></td>\n");
      out.write("	    		</tr>    \n");
      out.write("	    	</table>\n");
      out.write("	    </form>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div id=\"editDialog\" style=\"padding: 10px\">\n");
      out.write("    	<form id=\"editForm\" method=\"post\">\n");
      out.write("	    	<table cellpadding=\"8\" >\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>课程代码:</td>\n");
      out.write("	    			<td><input id=\"edit_cno\" class=\"easyui-textbox\" style=\"width: 200px; height: 30px;\" type=\"text\" name=\"cno\" readonly=\"readonly\" data-options=\"required:true,missingMessage:'请输入课程代码'\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>课程名:</td>\n");
      out.write("	    			<td><input id=\"edit_cname\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"cname\" data-options=\"required:true, missingMessage:'请填写课程名'\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>任课教师:</td>\n");
      out.write("	    			<td><input id=\"edit_tname\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"tname\" data-options=\"required:true, missingMessage:'请填写任课教师名'\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>学时:</td>\n");
      out.write("	    			<td><input id=\"edit_chour\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"chour\" /></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>学分:</td>\n");
      out.write("	    			<td><input id=\"edit_credit\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"credit\"/></td>\n");
      out.write("	    		</tr>\n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>考核形式:</td>\n");
      out.write("	    			<td><input id=\"edit_cway\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"cway\"/></td>\n");
      out.write("	    		</tr>  \n");
      out.write("	    		<tr>\n");
      out.write("	    			<td>学期:</td>\n");
      out.write("	    			<td><input id=\"edit_cdate\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"cdate\"/></td>\n");
      out.write("	    		</tr>    \n");
      out.write("	    	</table>\n");
      out.write("	    </form>\n");
      out.write("	</div>	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
