/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-07-11 08:56:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class scoreList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"UTF-8\">\n");
      out.write("	<title>学生列表</title>\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/css/demo.css\">\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/js/validateExtends.js\"></script>\n");
      out.write("	<script src=\"echarts.min.js\"></script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("	$(function() {	\n");
      out.write("		//datagrid初始化 \n");
      out.write("	    $('#dataList').datagrid({ \n");
      out.write("	        title:'学生列表', \n");
      out.write("	        iconCls:'icon-more',//图标 \n");
      out.write("	        border: true, \n");
      out.write("	        collapsible:false,//是否可折叠的 \n");
      out.write("	        fit: true,//自动大小 \n");
      out.write("	        method: \"post\",\n");
      out.write("	        url:\"AdminServlet?method=scoreList\",\n");
      out.write("	        idField:'cno', \n");
      out.write("	        singleSelect:false,//是否单选 \n");
      out.write("	        pagination:true,//分页控件 \n");
      out.write("	        rownumbers:true,//行号 \n");
      out.write("	        sortOrder:'Asc', \n");
      out.write("	        remoteSort: false,\n");
      out.write("	        queryParams:{grade:$(\"#gradeList\").combobox(\"getValue\")},\n");
      out.write("	        columns: [[  \n");
      out.write("				{field:'chk',checkbox: true,width:50},\n");
      out.write("				{field:'sno', title:'学号',width:100, sortable:true},\n");
      out.write("				{field:'sname', title:'姓名', width:100},\n");
      out.write("				{field:'GPA',title:'绩点',width:100,sortable:true}\n");
      out.write("	 		]], \n");
      out.write("	        toolbar: \"#toolbar\"\n");
      out.write("	    }); \n");
      out.write("	    //设置分页控件 \n");
      out.write("	    var p = $('#dataList').datagrid('getPager'); \n");
      out.write("	    $(p).pagination({ \n");
      out.write("	        pageSize: 10,//每页显示的记录条数，默认为10 \n");
      out.write("	        pageList: [10,20,30,50,100],//可以设置每页记录条数的列表 \n");
      out.write("	        beforePageText: '第',//页数文本框前显示的汉字 \n");
      out.write("	        afterPageText: '页    共 {pages} 页', \n");
      out.write("	        displayMsg: '当前显示 {from} - {to} 条记录   共 {total} 条记录', \n");
      out.write("	    }); \n");
      out.write("	    \n");
      out.write("	    \n");
      out.write("	    //查询按钮单击事件，利用学期查询和利用课程的模糊查询\n");
      out.write("	    $(\"#search\").click(function(){\n");
      out.write("	    	$(\"#dataList\").datagrid('load',{\n");
      out.write("	    		grade:$(\"#gradeList\").combobox(\"getValue\")\n");
      out.write("	    	});\n");
      out.write("	    });\n");
      out.write("	    \n");
      out.write("	  //导出按钮事件\n");
      out.write("	    $(\"#export\").click(function(){\n");
      out.write("	    	var grade = $(\"#gradeList\").combobox(\"getValue\");\n");
      out.write("	    	var url = \"AdminServlet?method=exportScoreList&grade=\"+ encodeURIComponent(grade);\n");
      out.write("	    	window.location.href = url;\n");
      out.write("	    });\n");
      out.write("	  \n");
      out.write("	    function generateChart() {\n");
      out.write("		    var grade = $(\"#gradeList\").combobox(\"getValue\");\n");
      out.write("		    console.log(\"Sending AJAX request with grade: \" + grade); // 添加日志\n");
      out.write("		    $.ajax({\n");
      out.write("		        url:\"AdminServlet?method=ChartOfScoreList\",\n");
      out.write("		        type: \"post\",\n");
      out.write("		        data: { grade: grade },\n");
      out.write("		        success: function(response) {\n");
      out.write("		        	console.log(\"Received response: \" + response);\n");
      out.write("		            var data = JSON.parse(response);\n");
      out.write("		            var names = [];\n");
      out.write("		            var scores = [];\n");
      out.write("		            for(var i = 0; i<data.length; i++)\n");
      out.write("		            	{\n");
      out.write("		            		scores.push({ value: data[i].GPA, name: data[i].sname });\n");
      out.write("		            	}\n");
      out.write("		            console.log(names);\n");
      out.write("		            \n");
      out.write("		            var chartDom = document.getElementById('myChart');\n");
      out.write("		            if (!chartDom) {\n");
      out.write("		            	console.error('Element #myChart not found');\n");
      out.write("		            	return;\n");
      out.write("		            }\n");
      out.write("		            var myChart = echarts.init(chartDom);\n");
      out.write("		            console.log(myChart);\n");
      out.write("		            myChart.showLoading();\n");
      out.write("		            var option = {\n");
      out.write("			                title: {\n");
      out.write("			                    text: '学生GPA图表',\n");
      out.write("			                    left: 'center'\n");
      out.write("			                },\n");
      out.write("			                tooltip: {\n");
      out.write("			                    trigger: 'item'\n");
      out.write("			                },\n");
      out.write("			                legend: {\n");
      out.write("			                    orient: 'vertical',\n");
      out.write("			                    left: 'left',\n");
      out.write("			                    show:false\n");
      out.write("			                },\n");
      out.write("			                series: [\n");
      out.write("			                    {\n");
      out.write("			                        name: 'GPA',\n");
      out.write("			                        type: 'pie',\n");
      out.write("			                        radius: '50%',\n");
      out.write("			                        data: scores,\n");
      out.write("			                        emphasis: {\n");
      out.write("			                            itemStyle: {\n");
      out.write("			                                shadowBlur: 10,\n");
      out.write("			                                shadowOffsetX: 0,\n");
      out.write("			                                shadowColor: 'rgba(0, 0, 0, 0.5)'\n");
      out.write("			                            }\n");
      out.write("			                        },\n");
      out.write("			                        label: {\n");
      out.write("			                            formatter: '{b}: {c} ({d}%)',\n");
      out.write("			                            position: 'outside'\n");
      out.write("			                        },\n");
      out.write("			                        labelLine: {\n");
      out.write("			                            length: 10,\n");
      out.write("			                            length2: 20\n");
      out.write("			                        },\n");
      out.write("			                        \n");
      out.write("			                    }\n");
      out.write("			                ]\n");
      out.write("			            };\n");
      out.write("		            console.log(option);\n");
      out.write("		            myChart.setOption(option);\n");
      out.write("		            myChart.hideLoading();\n");
      out.write("		            console.log(myChart);\n");
      out.write("		        },\n");
      out.write("		            \n");
      out.write("			     error: function() \n");
      out.write("			     	{\n");
      out.write("			           alert(\"获取数据失败！\");\n");
      out.write("			        }\n");
      out.write("			    });\n");
      out.write("		    }\n");
      out.write("		            \n");
      out.write("		            \n");
      out.write("	 // 新增生成图表按钮点击事件\n");
      out.write("	    $(\"#generateChart\").click(function() {\n");
      out.write("	    	$('#chartDialog').dialog('open');\n");
      out.write("           generateChart();\n");
      out.write("	    });\n");
      out.write("	 \n");
      out.write("	  	\n");
      out.write("	});  	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	</script>\n");
      out.write("	<style>\n");
      out.write("		#toolbar {\n");
      out.write("			overflow: hidden;\n");
      out.write("			padding: 5px;\n");
      out.write("		}\n");
      out.write("		#toolbar div {\n");
      out.write("			float: left;\n");
      out.write("			margin-right: 10px;\n");
      out.write("		}\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 学生列表 -->\n");
      out.write("	<table id=\"dataList\" cellspacing=\"0\" cellpadding=\"0\"> \n");
      out.write("	    \n");
      out.write("	</table> \n");
      out.write("	<!-- 工具栏 -->\n");
      out.write("	<div id=\"toolbar\">\n");
      out.write(" 		<div style=\"float: left; margin: 0 10px 0 10px\">学期：<select id=\"gradeList\" class=\"easyui-combobox\" name=\"grade\" >\n");
      out.write("	 			<option value=\"\">全部</option>\n");
      out.write("	 			<option value=\"2022-2023学年第1学期\">2022-2023学年第1学期</option>\n");
      out.write("	 			<option value=\"2022-2023学年第2学期\">2022-2023学年第2学期</option>\n");
      out.write("	 			<option value=\"2023-2024学年第1学期\">2023-2024学年第1学期</option>\n");
      out.write("	 			<option value=\"2023-2024学年第2学期\">2023-2024学年第2学期</option>\n");
      out.write("	 			<option value=\"2024-2025学年第1学期\">2024-2025学年第1学期</option>\n");
      out.write("	 			<option value=\"2024-2025学年第2学期\">2024-2025学年第2学期</option>\n");
      out.write("	 			<option value=\"2025-2026学年第1学期\">2025-2026学年第1学期</option>\n");
      out.write("	 			<option value=\"2025-2026学年第2学期\">2025-2026学年第2学期</option>\n");
      out.write(" 			</select>\n");
      out.write(" 		</div>\n");
      out.write("  		<div style=\"float: left;\"><a id=\"search\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-search',plain:true\">查询</a></div> \n");
      out.write("		<div style=\"float: right;\"><a id=\"export\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-print',plain:true\">导出数据</a></div>\n");
      out.write("		<div style=\"float: right; margin-right: 10px;\">\n");
      out.write("    		<a id=\"generateChart\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-chart_bar',plain:true\">生成图表</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<!-- 图表显示区域 -->\n");
      out.write("	<div id=\"chartDialog\" class=\"easyui-dialog\" title=\"学生GPA图表\" style=\"width:650px;height:450px;padding:10px\" \n");
      out.write("		data-options=\"closed:true, modal:true\">\n");
      out.write("	    <div id=\"myChart\" style=\"width:600px;height:400px;\"></div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
