/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-08-06 13:57:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class userList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>用户列表</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/default/easyui.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/themes/icon.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"easyui/css/demo.css\">\r\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"easyui/js/validateExtends.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {	\r\n");
      out.write("		\r\n");
      out.write("	    $('#dataList').datagrid({ \r\n");
      out.write("	        title:'用户列表', \r\n");
      out.write("	        iconCls:'icon-more',//图标 \r\n");
      out.write("	        border: true, \r\n");
      out.write("	        collapsible:false,//是否可折叠的 \r\n");
      out.write("	        fit: true,//自动大小 \r\n");
      out.write("	        method: \"post\",\r\n");
      out.write("	        url:\"AdminServlet?method=userList\",\r\n");
      out.write("	        idField:'account', \r\n");
      out.write("	        singleSelect:false,//是否单选 \r\n");
      out.write("	        pagination:true,//分页控件 \r\n");
      out.write("	        rownumbers:true,//行号 \r\n");
      out.write("	        sortName:'account',\r\n");
      out.write("	        sortOrder:'ASC', \r\n");
      out.write("	        remoteSort: false,\r\n");
      out.write("	        columns: [[  \r\n");
      out.write("				{field:'chk',checkbox: true,width:50},		       \r\n");
      out.write(" 		        {field:'account',title:'账号',width:150, sortable:true},\r\n");
      out.write(" 		        {field:'name',title:'姓名',width:100},\r\n");
      out.write(" 		        {field:'password',title:'密码',width:150},\r\n");
      out.write(" 		        {field:'role',title:'用户类别',width:100,\r\n");
      out.write(" 		        	formatter:function(value,row,index)\r\n");
      out.write(" 		        	{\r\n");
      out.write(" 		        		// 根据当前域的值，返回是学生，教师还是管理员\r\n");
      out.write(" 		        		if(value == 0)\r\n");
      out.write(" 		        			{\r\n");
      out.write(" 		        				return '学生';\r\n");
      out.write(" 		        			}\r\n");
      out.write(" 		        		else if(value == 1)\r\n");
      out.write(" 		        			{\r\n");
      out.write(" 		        				return '教师';\r\n");
      out.write(" 		        			}\r\n");
      out.write(" 		        		else if(value == 2)\r\n");
      out.write(" 		        			{\r\n");
      out.write(" 		        				return '管理员';\r\n");
      out.write(" 		        			}\r\n");
      out.write(" 		        	}}\r\n");
      out.write("	 		]], \r\n");
      out.write("	        toolbar: \"#toolbar\"\r\n");
      out.write("	    }); \r\n");
      out.write("	     \r\n");
      out.write("	    var p = $('#dataList').datagrid('getPager'); \r\n");
      out.write("	    $(p).pagination({ \r\n");
      out.write("	        pageSize: 10,//每页显示的记录条数，默认为10 \r\n");
      out.write("	        pageList: [10,20,30,50,100],//可以设置每页记录条数的列表 \r\n");
      out.write("	        beforePageText: '第',//页数文本框前显示的汉字 \r\n");
      out.write("	        afterPageText: '页    共 {pages} 页', \r\n");
      out.write("	        displayMsg: '当前显示 {from} - {to} 条记录   共 {total} 条记录', \r\n");
      out.write("	    });\r\n");
      out.write("	    //添加\r\n");
      out.write("	    $(\"#add\").click(function(){\r\n");
      out.write("	    	$(\"#addDialog\").dialog(\"open\");\r\n");
      out.write("	    });\r\n");
      out.write("	  	//修改\r\n");
      out.write("	    $(\"#edit\").click(function(){\r\n");
      out.write("	    	var selectRows = $(\"#dataList\").datagrid(\"getSelections\");\r\n");
      out.write("        	if(selectRows.length != 1){\r\n");
      out.write("            	$.messager.alert(\"消息提醒\", \"请选择一条数据进行操作!\", \"warning\");\r\n");
      out.write("            } else{\r\n");
      out.write("		    	$(\"#editDialog\").dialog(\"open\");\r\n");
      out.write("            }\r\n");
      out.write("	    });\r\n");
      out.write("	  	//删除\r\n");
      out.write("	    $(\"#delete\").click(function(){\r\n");
      out.write("	    	var selectRow = $(\"#dataList\").datagrid(\"getSelected\");\r\n");
      out.write("        	if(selectRow == null){\r\n");
      out.write("            	$.messager.alert(\"消息提醒\", \"请选择数据进行删除!\", \"warning\");\r\n");
      out.write("            } else{\r\n");
      out.write("            	var account = selectRow.account;\r\n");
      out.write("            	$.messager.confirm(\"消息提醒\", \"将删除与用户相关的所有数据，确认继续？\", function(r){\r\n");
      out.write("            		if(r){\r\n");
      out.write("            			$.ajax({\r\n");
      out.write("							type: \"post\",\r\n");
      out.write("							url: \"AdminServlet?method=deleteUser\",\r\n");
      out.write("							data: {account: account},\r\n");
      out.write("							success: function(msg){\r\n");
      out.write("								if(msg == \"success\"){\r\n");
      out.write("									$.messager.alert(\"消息提醒\",\"删除成功!\",\"info\");\r\n");
      out.write("									//刷新表格\r\n");
      out.write("									$(\"#dataList\").datagrid(\"reload\");\r\n");
      out.write("									$(\"#dataList\").datagrid(\"uncheckAll\");\r\n");
      out.write("								} else{\r\n");
      out.write("									$.messager.alert(\"消息提醒\",\"删除失败!\",\"warning\");\r\n");
      out.write("									return;\r\n");
      out.write("								}\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("            		}\r\n");
      out.write("            	});\r\n");
      out.write("            }\r\n");
      out.write("	    });\r\n");
      out.write("	  	\r\n");
      out.write("	  //导出按钮事件\r\n");
      out.write("	    $(\"#export\").click(function(){\r\n");
      out.write("	    	var url = \"AdminServlet?method=exportUserList\";\r\n");
      out.write("	    	window.location.href = url;\r\n");
      out.write("	    });\r\n");
      out.write("	  \r\n");
      out.write("	  	//设置添加用户窗口\r\n");
      out.write("	    $(\"#addDialog\").dialog({\r\n");
      out.write("	    	title: \"添加用户\",\r\n");
      out.write("	    	width: 650,\r\n");
      out.write("	    	height: 460,\r\n");
      out.write("	    	iconCls: \"icon-add\",\r\n");
      out.write("	    	modal: true,\r\n");
      out.write("	    	collapsible: false,\r\n");
      out.write("	    	minimizable: false,\r\n");
      out.write("	    	maximizable: false,\r\n");
      out.write("	    	draggable: true,\r\n");
      out.write("	    	closed: true,\r\n");
      out.write("	    	buttons: [\r\n");
      out.write("	    		{\r\n");
      out.write("					text:'添加',\r\n");
      out.write("					plain: true,\r\n");
      out.write("					iconCls:'icon-user_add',\r\n");
      out.write("					handler:function(){\r\n");
      out.write("						var validate = $(\"#addForm\").form(\"validate\");\r\n");
      out.write("						if(!validate){\r\n");
      out.write("							$.messager.alert(\"消息提醒\",\"请检查你输入的数据!\",\"warning\");\r\n");
      out.write("							return;\r\n");
      out.write("						} else{\r\n");
      out.write("							$.ajax({\r\n");
      out.write("								type: \"post\",\r\n");
      out.write("								url: \"AdminServlet?method=addUser\",\r\n");
      out.write("								data: $(\"#addForm\").serialize(),\r\n");
      out.write("								success: function(msg){\r\n");
      out.write("									if(msg == \"success\"){\r\n");
      out.write("										$.messager.alert(\"消息提醒\",\"添加成功!\",\"info\");\r\n");
      out.write("										//关闭窗口\r\n");
      out.write("										$(\"#addDialog\").dialog(\"close\");\r\n");
      out.write("										//清空原表格数据\r\n");
      out.write("										$(\"#add_account\").textbox('setValue', \"\");\r\n");
      out.write("										$(\"#add_name\").textbox('setValue', \"\");\r\n");
      out.write("										$(\"#add_password\").textbox('setValue', \"\");\r\n");
      out.write("										$(\"#add_role\").textbox('setValue', \"\");\r\n");
      out.write("										//重新刷新页面数据\r\n");
      out.write("							  			$('#dataList').datagrid(\"reload\");	\r\n");
      out.write("									} else{\r\n");
      out.write("										$.messager.alert(\"消息提醒\",\"添加失败!\",\"warning\");\r\n");
      out.write("										return;\r\n");
      out.write("									}\r\n");
      out.write("								}\r\n");
      out.write("							});\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				{\r\n");
      out.write("					text:'重置',\r\n");
      out.write("					plain: true,\r\n");
      out.write("					iconCls:'icon-reload',\r\n");
      out.write("					handler:function(){\r\n");
      out.write("						$(\"#add_account\").textbox('setValue', \"\");\r\n");
      out.write("						$(\"#add_name\").textbox('setValue', \"\");\r\n");
      out.write("						$(\"#add_password\").textbox('setValue', \"\");\r\n");
      out.write("						$(\"#add_role\").textbox('setValue', \"\");\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("			]\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	  \r\n");
      out.write("		//设置编辑用户窗口\r\n");
      out.write("	    $(\"#editDialog\").dialog({\r\n");
      out.write("	    	title: \"修改用户信息\",\r\n");
      out.write("	    	width: 650,\r\n");
      out.write("	    	height: 460,\r\n");
      out.write("	    	iconCls: \"icon-edit\",\r\n");
      out.write("	    	modal: true,\r\n");
      out.write("	    	collapsible: false,\r\n");
      out.write("	    	minimizable: false,\r\n");
      out.write("	    	maximizable: false,\r\n");
      out.write("	    	draggable: true,\r\n");
      out.write("	    	closed: true,\r\n");
      out.write("	    	buttons: [\r\n");
      out.write("	    		{\r\n");
      out.write("					text:'提交',\r\n");
      out.write("					plain: true,\r\n");
      out.write("					iconCls:'icon-user_add',\r\n");
      out.write("					handler:function(){\r\n");
      out.write("						var validate = $(\"#editForm\").form(\"validate\");\r\n");
      out.write("						if(!validate){\r\n");
      out.write("							$.messager.alert(\"消息提醒\",\"请检查你输入的数据!\",\"warning\");\r\n");
      out.write("							return;\r\n");
      out.write("						} else{\r\n");
      out.write("							$.ajax({\r\n");
      out.write("								type: \"post\",\r\n");
      out.write("								url: \"AdminServlet?method=editUser\",\r\n");
      out.write("								data: $(\"#editForm\").serialize(),\r\n");
      out.write("								success: function(msg){\r\n");
      out.write("									if(msg == \"success\"){\r\n");
      out.write("										$.messager.alert(\"消息提醒\",\"更新成功!\",\"info\");\r\n");
      out.write("										//关闭窗口\r\n");
      out.write("										$(\"#editDialog\").dialog(\"close\");\r\n");
      out.write("										//刷新表格\r\n");
      out.write("										$(\"#dataList\").datagrid(\"reload\");\r\n");
      out.write("										$(\"#dataList\").datagrid(\"uncheckAll\");						  			\r\n");
      out.write("									} else{\r\n");
      out.write("										$.messager.alert(\"消息提醒\",\"更新失败!\",\"warning\");\r\n");
      out.write("										return;\r\n");
      out.write("									}\r\n");
      out.write("								}\r\n");
      out.write("							});\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				{\r\n");
      out.write("					text:'重置',\r\n");
      out.write("					plain: true,\r\n");
      out.write("					iconCls:'icon-reload',\r\n");
      out.write("					handler:function(){\r\n");
      out.write("						var role;\r\n");
      out.write("						//清空表单\r\n");
      out.write("						$(\"#edit_account\").textbox('setValue', selectRow.account);\r\n");
      out.write("						$(\"#edit_name\").textbox('setValue', selectRow.name);\r\n");
      out.write("						$(\"#edit_password\").textbox('setValue', selectRow.password);\r\n");
      out.write("						if(selectRow.role==0)\r\n");
      out.write("							{\r\n");
      out.write("								role=\"学生\";\r\n");
      out.write("							}\r\n");
      out.write("						else if(selectRow.role==1)\r\n");
      out.write("							{\r\n");
      out.write("								role=\"教师\";\r\n");
      out.write("							}\r\n");
      out.write("						else if(selectRow.role==2)\r\n");
      out.write("							{\r\n");
      out.write("								role=\"管理员\";\r\n");
      out.write("							}\r\n");
      out.write("						$(\"#edit_role\").textbox('setValue', role);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			],\r\n");
      out.write("			onBeforeOpen: function(){\r\n");
      out.write("				var selectRow = $(\"#dataList\").datagrid(\"getSelected\");\r\n");
      out.write("				var role;\r\n");
      out.write("				//设置值\r\n");
      out.write("				$(\"#edit_account\").textbox('setValue', selectRow.account);\r\n");
      out.write("				$(\"#edit_name\").textbox('setValue', selectRow.name);\r\n");
      out.write("				$(\"#edit_password\").textbox('setValue', selectRow.password);\r\n");
      out.write("				if(selectRow.role==0)\r\n");
      out.write("				{\r\n");
      out.write("					role=\"学生\";\r\n");
      out.write("				}\r\n");
      out.write("			else if(selectRow.role==1)\r\n");
      out.write("				{\r\n");
      out.write("					role=\"教师\";\r\n");
      out.write("				}\r\n");
      out.write("			else if(selectRow.role==2)\r\n");
      out.write("				{\r\n");
      out.write("					role=\"管理员\";\r\n");
      out.write("				}\r\n");
      out.write("				$(\"#edit_role\").textbox('setValue', role);\r\n");
      out.write("			}\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("	</script>\r\n");
      out.write("	<style>\r\n");
      out.write("		#toolbar {\r\n");
      out.write("			overflow: hidden;\r\n");
      out.write("			padding: 5px;\r\n");
      out.write("		}\r\n");
      out.write("		#toolbar div {\r\n");
      out.write("			float: left;\r\n");
      out.write("			margin-right: 10px;\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<table id=\"dataList\" cellspacing=\"0\" cellpadding=\"0\"> \r\n");
      out.write("	    \r\n");
      out.write("	</table> \r\n");
      out.write("	<!-- 工具栏 -->\r\n");
      out.write("	<div id=\"toolbar\">\r\n");
      out.write("		<div style=\"float: left;\"><a id=\"add\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add',plain:true\">添加</a></div>\r\n");
      out.write("			<div style=\"float: left;\" class=\"datagrid-btn-separator\"></div>\r\n");
      out.write("		<div style=\"float: left;\"><a id=\"edit\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-edit',plain:true\">修改</a></div>\r\n");
      out.write("			<div style=\"float: left;\" class=\"datagrid-btn-separator\"></div>\r\n");
      out.write("		<div><a id=\"delete\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-some-delete',plain:true\">删除</a></div>\r\n");
      out.write("		<div style=\"float: right;\"><a id=\"export\" href=\"javascript:;\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-print',plain:true\">导出数据</a></div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"addDialog\" style=\"padding: 10px\">\r\n");
      out.write("    	<form id=\"addForm\" method=\"post\">\r\n");
      out.write("	    	<table cellpadding=\"8\" >\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>账号:</td>\r\n");
      out.write("	    			<td><input id=\"add_account\" class=\"easyui-textbox\" style=\"width: 200px; height: 30px;\" type=\"text\" name=\"account\" data-options=\"required:true,missingMessage:'请输入账号'\" /></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>姓名:</td>\r\n");
      out.write("	    			<td><input id=\"add_name\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"name\" data-options=\"required:true, missingMessage:'请填写姓名'\" /></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>密码:</td>\r\n");
      out.write("	    			<td><input id=\"add_password\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"password\" name=\"password\" data-options=\"required:true, missingMessage:'请填写密码'\" /></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>用户类别:</td>\r\n");
      out.write("	    			<td><select id=\"add_role\" class=\"easyui-combobox\" data-options=\"editable: false, panelHeight: 50, width: 60, height: 30\" name=\"role\"><option value=0>学生</option><option value=1>教师</option><option value=2>管理员</option></select></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    	</table>\r\n");
      out.write("	    </form>\r\n");
      out.write("	</div>	\r\n");
      out.write("\r\n");
      out.write("	<div id=\"editDialog\" style=\"padding: 10px\">\r\n");
      out.write("    	<form id=\"editForm\" method=\"post\">\r\n");
      out.write("	    	<table cellpadding=\"8\" >\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>账号:</td>\r\n");
      out.write("	    			<td><input id=\"edit_account\" class=\"easyui-textbox\" style=\"width: 200px; height: 30px;\" type=\"text\" name=\"account\" data-options=\"required:true,missingMessage:'请输入账号'\" /></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>姓名:</td>\r\n");
      out.write("	    			<td><input id=\"edit_name\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"text\" name=\"name\" data-options=\"required:true, missingMessage:'请填写姓名'\" /></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>密码:</td>\r\n");
      out.write("	    			<td><input id=\"edit_password\" style=\"width: 200px; height: 30px;\" class=\"easyui-textbox\" type=\"password\" name=\"password\" data-options=\"required:true, missingMessage:'请填写密码'\" /></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    		<tr>\r\n");
      out.write("	    			<td>用户类别:</td>\r\n");
      out.write("	    			<td><select id=\"edit_role\" class=\"easyui-combobox\" data-options=\"editable: false, panelHeight: 50, width: 60, height: 30\" name=\"role\"><option value=0>学生</option><option value=1>教师</option><option value=2>管理员</option></select></td>\r\n");
      out.write("	    		</tr>\r\n");
      out.write("	    	</table>\r\n");
      out.write("	    </form>\r\n");
      out.write("	</div>	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
